set autoindent
set clipboard^=unnamed clipboard^=unnamedplus
set colorcolumn=80
if !has('nvim')
  set completeopt-=preview completeopt+=popup
endif
set conceallevel=2
set cursorline
set diffopt+=iwhiteall
set directory=/tmp
set display=lastline
set expandtab
set nofileignorecase
set foldmethod=syntax
set formatoptions=tcqj
set grepprg=grep\ -nrs\ $*\ /dev/null
if has('nvim')
  set nohidden
endif
set hlsearch
set incsearch
set nojoinspaces
set mouse=a
set number
set regexpengine=0
if has('nvim')
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath
endif
set sessionoptions-=blank sessionoptions-=buffers sessionoptions-=options
set shiftwidth=2
set showcmd
set spell
set tabstop=2
set viewoptions-=options
set wildmenu
filetype plugin indent on
syntax on
colorscheme sierra
highlight ColorColumn ctermbg=NONE
highlight CursorLine ctermbg=NONE
highlight CursorLineNr ctermbg=NONE
highlight LineNr ctermbg=NONE
highlight Normal ctermbg=NONE
highlight VertSplit ctermbg=NONE
highlight WinSeparator ctermbg=NONE
let $BASHOPTS = 'globstar'
let $BASH_ENV = '~/.bash_aliases'
let g:airline#extensions#branch#format = 2
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1
let g:ale_completion_enabled = 1
let g:ale_fixers = {
  \ 'c': ['clang-format'],
  \ 'cpp': ['clang-format'],
  \ 'cuda': ['clang-format'],
  \ 'python': ['black'],
  \ 'tex': ['latexindent'],
  \ '*': ['prettier']
\ }
let g:ale_fix_on_save = 1
if has('popupwin') || has('nvim')
  let g:ale_hover_to_floating_preview = 1
endif
let g:ale_set_balloons = 1
let g:ale_virtualtext_cursor = 0
let g:ctrlp_custom_ignore =
    \ '\v\/((([^\/]*[^A-Za-z])?build|devel|dist|logs)|\.\w*cache|\.catkin_tools|\.clangd\/index|\.git|\.venv|__pycache__|node_modules|third_?party)$'
let g:ctrlp_max_files = 100000
let g:ctrlp_show_hidden = 1
let g:ctrlp_working_path_mode = 0
let g:DevIconsEnableFoldersOpenClose = 1
let g:NERDTreeGitStatusUseNerdFonts = 1
let g:NERDTreeShowHidden = 1
let g:vimtex_fold_enabled = 1
let g:vimtex_view_method = 'zathura'
packloadall
packadd vim-devicons
packadd nerdtree-git-plugin
packadd nerdtree
helptags ALL
function AddAlignment()
  let l:begin = search('\$\$', 'bcnW')
  let l:end = search('\$\$', 'nW')
  if l:begin != 0 && l:end != 0
    execute l:begin . 'substitute/\$\$/\\begin{align*}/'
    execute l:end . 'substitute/\$\$/\\end{align*}/'
    if l:end - l:begin >= 2
      execute (l:begin + 1) . ',' . (l:end - 1) .
          \ 'substitute/\v:?\=|\<\>|\\[gln]e|\\approx|\\in|\\propto|\\sim|\\subset(eq)?/\&\0/'
    endif
    if l:end - l:begin >= 3
      execute (l:begin + 1) . ',' . (l:end - 2) . 'substitute/$/ \\\\/'
    endif
  endif
endfunction
function s:AppendPandocMessage(bufnr, _channel, data, ...)
  call timer_stop(getbufvar(a:bufnr, 'pandoc_timer', 0))
  let l:pandoc_messages = getbufvar(a:bufnr, 'pandoc_messages')
  if has('nvim')
    if a:data !=# ['']
      if empty(l:pandoc_messages)
        call add(l:pandoc_messages, {'text': ''})
      endif
      let l:pandoc_messages[-1].text .= a:data[0]
      call extend(
        \ l:pandoc_messages,
        \ map(a:data[1:], {_index, message -> {'text': message}})
      \ )
    endif
  else
    call add(l:pandoc_messages, {'text': a:data})
  endif
  call setbufvar(
    \ a:bufnr,
    \ 'pandoc_timer',
    \ timer_start(600, function('s:EchoPandocMessages', [a:bufnr]))
  \ )
endfunction
function s:BufClean()
  for l:bufnr in range(1, bufnr('$'))
    if buflisted(l:bufnr) && empty(win_findbuf(l:bufnr))
      execute 'bdelete!' l:bufnr
    endif
  endfor
endfunction
function s:CloseFugitiveIndices()
  for l:bufnr in range(1, bufnr('$'))
    if getbufvar(l:bufnr, 'fugitive_type') ==# 'index'
      execute 'bdelete' l:bufnr
    endif
  endfor
endfunction
function CopilotChatToggle()
  let l:winnr = bufwinnr(g:copilot_chat_active_buffer)
  if l:winnr != -1
    execute l:winnr 'close'
  else
    let l:curwinid = win_getid()
    for l:winid in win_findbuf(g:copilot_chat_active_buffer)
      call win_gotoid(l:winid)
      close
    endfor
    call win_gotoid(l:curwinid)
    CopilotChatToggle
    normal G
    startinsert
  endif
endfunction
function DetailHoverCodeAction()
  if !empty(ale#util#FindItemAtCursor(bufnr())[1])
    ALEDetail
  else
    ALEHover
    ALECodeAction
  endif
endfunction
function DiffDisk()
  vertical new
  setlocal buftype=nofile
  read ++edit #
  1delete _
  diffthis
  wincmd p
  diffthis
endfunction
function DrawerFind()
  let l:bufnr = bufnr()
  let l:curwinid = win_getid()
  if !g:NERDTree.IsOpen()
    call s:DrawerOpen()
  endif
  execute l:bufnr 'bufdo NERDTreeFind'
  if !empty(FugitiveGitDir(l:bufnr))
    wincmd j
    execute 'buffer' l:bufnr
    Gedit :
    normal zR
  endif
  call win_gotoid(l:curwinid)
endfunction
function s:DrawerOpen()
  let l:bufnr = bufnr()
  NERDTreeFocus
  if !empty(FugitiveGitDir(l:bufnr))
    execute 'belowright sbuffer' l:bufnr
    Gedit :
    normal zR
  endif
endfunction
function DrawerToggle()
  let l:curwinid = win_getid()
  if g:NERDTree.IsOpen()
    NERDTreeClose
    call s:FugitiveClose()
  else
    call s:DrawerOpen()
  endif
  call win_gotoid(l:curwinid)
endfunction
function s:EchoPandocMessages(bufnr, _timer)
  let l:pandoc_messages = getbufvar(a:bufnr, 'pandoc_messages')
  call setqflist(l:pandoc_messages)
  if !empty(l:pandoc_messages)
    call s:QuickFixOpen()
  endif
  call setbufvar(a:bufnr, 'pandoc_messages', [])
endfunction
function s:FugitiveClose()
  for l:winnr in range(1, winnr('$'))
    let l:bufnr = winbufnr(l:winnr)
    if getbufvar(l:bufnr, 'fugitive_type') ==# 'index'
      execute 'bdelete' l:bufnr
    endif
  endfor
endfunction
function GoToDefinition()
  try
    execute "normal! \<C-]>"
  catch
    ALEGoToDefinition
  endtry
endfunction
function GoToTerminal()
  for l:winnr in range(1, winnr('$'))
    if getbufvar(winbufnr(l:winnr), '&buftype') ==# 'terminal'
      execute l:winnr 'wincmd w'
      return
    endif
  endfor
endfunction
function s:Hover(line, column)
  let l:bufnr = bufnr()
  let b:ale_set_balloons = 0
  call timer_start(
    \ 600,
    \ {-> setbufvar(l:bufnr, 'ale_set_balloons', g:ale_set_balloons)}
  \ )
  call ale#hover#Show(
    \ l:bufnr,
    \ a:line,
    \ a:column,
    \ {'called_from_balloonexpr': v:true}
  \ )
endfunction
function HoverFunctionCall()
  let l:curpos = getpos('.')
  let [l:line, l:column] = searchpos('(', 'bcnW')
  if l:line == l:curpos[1] && l:column == l:curpos[2] - 1
    call s:Hover(l:line, l:column)
  else
    let &operatorfunc = function('s:HoverOperator', [winsaveview()])
    normal g@[(
  endif
endfunction
function s:HoverOneBack()
  if !empty(v:completed_item)
    let l:curpos = getpos('.')
    call s:Hover(l:curpos[1], l:curpos[2] - 1)
  endif
endfunction
function s:HoverOperator(view, type)
  call winrestview(a:view)
  let l:operatorpos = getpos("'[")
  call s:Hover(l:operatorpos[1], l:operatorpos[2])
endfunction
function PandocWorkerToggle()
  if get(b:, 'pandoc_job', v:null) is v:null
    let l:bufnr = bufnr()
    let l:source = expand('%:t')
    let l:target = '/tmp/' . fnamemodify(l:source, ':r') . '.pdf'
    let l:pandoc_command =
        \ 'inwm ' . l:source . ' pandoc -o ' . l:target . ' ' . l:source
    let l:zathura_command =
        \ 'inotifywait --event modify --quiet ' . l:target . ' && zathura ' .
        \ l:target
    let b:pandoc_messages = []
    call system('touch ' . l:target)
    if has('nvim')
      let b:pandoc_job = jobstart(
        \ l:pandoc_command,
        \ {
          \ 'cwd': expand('%:h'),
          \ 'on_stderr': function('s:AppendPandocMessage', [l:bufnr])
        \ }
      \ )
      let b:zathura_job = jobstart(l:zathura_command)
    else
      let b:pandoc_job = job_start(
        \ ['bash', '-c', l:pandoc_command],
        \ {
          \ 'cwd': expand('%:h'),
          \ 'err_cb': function('s:AppendPandocMessage', [l:bufnr])
        \ }
      \ )
      let b:zathura_job = job_start(['bash', '-c', l:zathura_command])
    endif
    let b:ale_fix_on_save = 0
    call timer_start(200, function('execute', [l:bufnr . 'bufdo write']))
  else
    if has('nvim')
      call jobstop(b:pandoc_job)
      call jobstop(b:zathura_job)
    else
      call job_stop(b:pandoc_job)
      call job_stop(b:zathura_job)
    endif
    let b:pandoc_job = v:null
    unlet b:ale_fix_on_save
    cclose
  endif
endfunction
function s:Persist()
  if !empty(v:this_session) && !exists('g:SessionLoad')
    silent! execute 'mksession!' v:this_session
  endif
endfunction
function s:PersistAndCloseTerminals()
  if !empty(v:this_session) && empty(filter(range(1, bufnr('$')), {
    \ _index, bufnr ->
        \ getbufvar(bufnr, '&modified') &&
        \ getbufvar(bufnr, '&buftype') !=# 'terminal'
  \ }))
    augroup squiffles
      autocmd! BufEnter *
    augroup end
    call s:CloseFugitiveIndices()
    execute 'mksession!' v:this_session
    if !has('nvim')
      for l:bufnr in range(1, bufnr('$'))
        if getbufvar(l:bufnr, '&buftype') ==# 'terminal'
          call term_sendkeys(l:bufnr, "\<C-D>")
        endif
      endfor
      sleep 100m
      for l:bufnr in range(1, bufnr('$'))
        if stridx(term_getstatus(l:bufnr), 'running') != -1
          execute 'bdelete!' l:bufnr
        endif
      endfor
    endif
  endif
endfunction
function QuickFixDifferentFile(operator)
  let l:qflist = getqflist({'id': 0, 'idx': 0, 'items': [], 'size': 0})
  let l:current = l:qflist.idx - 1
  let l:bufnr = l:qflist.items[l:current].bufnr
  for l:delta in range(1, l:qflist.size - 1)
    let l:other =
        \ (a:operator(l:current, l:delta) + l:qflist.size) % l:qflist.size
    if l:qflist.items[l:other].bufnr != l:bufnr
      execute 'cc' l:other + 1
      return
    endif
  endfor
endfunction
function s:QuickFixOpen()
  let l:curwinid = win_getid()
  cclose
  wincmd b
  vertical rightbelow copen 80
  call win_gotoid(l:curwinid)
endfunction
function QuickFixToggle()
  for l:winnr in range(1, winnr('$'))
    if getbufvar(winbufnr(l:winnr), '&buftype') ==# 'quickfix'
      cclose
      return
    endif
  endfor
  call s:QuickFixOpen()
endfunction
function s:ReopenTerminals(_timer)
  let l:curwinid = win_getid()
  for l:bufnr in range(1, bufnr('$'))
    if getbufvar(l:bufnr, '&buftype') ==# 'terminal' ||
        \ bufname(l:bufnr)[0:6] ==# 'term://'
      for l:bufwinid in win_findbuf(l:bufnr)
        call win_gotoid(l:bufwinid)
        if has('nvim')
          terminal
        else
          enew!
          terminal ++curwin
        endif
      endfor
    endif
  endfor
  call win_gotoid(l:curwinid)
  call s:BufClean()
endfunction
function s:RestoreLayout()
  call s:CloseFugitiveIndices()
  call timer_stop(get(s:, 'terminals_timer', 0))
  let s:terminals_timer = timer_start(200, function('s:ReopenTerminals'))
  if !empty(v:this_session)
    call rename(v:this_session, v:this_session . '~')
  endif
endfunction
augroup squiffles
  autocmd!
  autocmd BufEnter * call s:Persist()
  autocmd CompleteDone * call s:HoverOneBack()
  autocmd ExitPre * call s:PersistAndCloseTerminals()
  autocmd FileType markdown noremap <buffer> <Leader>ll <Cmd>call PandocWorkerToggle()<CR>
  autocmd FileType php setlocal foldmethod=indent
  autocmd FileType python setlocal foldmethod=indent
  autocmd SessionLoadPost * call s:RestoreLayout()
  if has('nvim')
    autocmd TermOpen * setlocal nonumber nospell
  endif
augroup end
command BC call s:BufClean()
cabbrev bc BC
cabbrev ccc CtrlPClearAllCaches
cabbrev ccr CopilotChatReset
command DD call DiffDisk()
cabbrev dd DD
command -complete=customlist,fugitive#LogComplete -nargs=* GLAG
    \ Git log --date-order --format=glag --graph <args>
cabbrev glag GLAG
if has('nvim')
  cabbrev term split \| terminal
  cabbrev terminal split \| terminal
endif
noremap <C-L> <Cmd>call DetailHoverCodeAction()<CR>
inoremap <C-L> <C-\><C-O>:call HoverFunctionCall()<CR>
noremap <C-LeftMouse> <LeftMouse><Cmd>call GoToDefinition()<CR>
if has('nvim')
  tnoremap <C-W> <C-\><C-N><C-W>
endif
tmap <C-W>: <C-\><C-N>:vertical terminal<CR><C-\><C-N><C-W>li<C-W>hi
noremap <C-W>; <Cmd>call GoToTerminal()<CR><C-\><C-N>i<Esc>a
noremap <C-]> <Cmd>call GoToDefinition()<CR>
noremap <Leader>cc <Cmd>call CopilotChatToggle()<CR>
vmap <Leader>cs <Plug>CopilotChatAddSelection
noremap <Leader>f <Cmd>call DrawerFind()<CR>
noremap <Leader>l$ <Cmd>call AddAlignment()<CR>
noremap <Leader>q <Cmd>noautocmd call QuickFixToggle()<CR>
noremap <Leader>t <Cmd>call DrawerToggle()<CR>
noremap [l <Cmd>try <Bar> lprev <Bar> catch <Bar> try <Bar> llast <Bar> catch <Bar> ALEPreviousWrap <Bar> endtry <Bar> endtry<CR>
noremap ]l <Cmd>try <Bar> lnext <Bar> catch <Bar> try <Bar> lfirst <Bar> catch <Bar> ALENextWrap <Bar> endtry <Bar> endtry<CR>
noremap [Q <Cmd>call QuickFixDifferentFile({a, b -> a - b})<CR>
noremap ]Q <Cmd>call QuickFixDifferentFile({a, b -> a + b})<CR>
noremap [q <Cmd>try <Bar> cprev <Bar> catch <Bar> clast <Bar> endtry<CR>
noremap ]q <Cmd>try <Bar> cnext <Bar> catch <Bar> cfirst <Bar> endtry<CR>
nnoremap Y y$
nnoremap y<C-R>% <Cmd>let @" = @% <Bar> let @* = @% <Bar> let @+ = @%<CR>
