alias cacc="catkin build -DCMAKE_EXPORT_COMPILE_COMMANDS=1 && roscd && jq --slurp 'map(.[])' ../build/*/compile_commands.json > ../compile_commands.json"
alias glag='git log --all --graph'
glep() { grep --color=always --line-number "$@" | less --quit-if-one-screen --RAW-CONTROL-CHARS; }
export PATH="/usr/local/texlive/2022/bin/x86_64-linux:$PATH"
shopt -s globstar
