set autoindent
set clipboard=unnamedplus
set cursorline
set expandtab
set hlsearch
set incsearch
set mouse=a
set number
set shiftwidth=2
set smartindent
set tabstop=2
set wildmenu
colorscheme elflord
let g:NERDTreeWinPos = 'right'
let g:airline_powerline_fonts = 1
let g:ale_completion_enabled = 1
let g:ale_fixers = {'python': ['black']}
let g:ale_fix_on_save = 1
let g:ctrlp_custom_ignore = '\v[\/]\.git$|\v[\/]node_modules$'
let g:NERDTreeExactMatchHighlightFullName = 1
let g:NERDTreeFileExtensionHighlightFullName = 1
let g:NERDTreeGitStatusConcealBrackets = 1
let g:NERDTreePatternMatchHighlightFullName = 1
packadd! CtrlP
packadd! ale

