set clipboard=unnamedplus
set expandtab
set hlsearch
set incsearch
set mouse=a
set number
set shiftwidth=2
set tabstop=2
set wildmenu
colorscheme elflord
let g:NERDTreeWinPos = 'right'
let g:ale_completion_enabled = 1
let g:ctrlp_custom_ignore = '\v[\/]\.git$|\v[\/]node_modules$'
packadd! CtrlP
packadd! ale

